apiVersion: v1
kind: Pod
metadata:
  name: bftest-httpserver
  labels:
    app: bftest-httpserver
spec:
  #nodeSelector:
  #  kubernetes.io/hostname: master3
  containers:
  - name: bftest-httpserver
    image: python
    ports:
      - name: web
        containerPort: 61234
        protocol: TCP
    command: [ "/bin/sh", "-c", "python3 -m http.server 61234" ]
    securityContext:
      capabilities:
        add:
          - ALL
        runAsUser: 0
        runAsGroup: 0

