---
# Source: social-distancing-retail/charts/grafana-mcss/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-mcss
  namespace: devcloudexample
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-abcxzy
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: grafana-abcxzy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: grafana-abcxzy
    spec:
      containers:
      - name: grafana-mcss
        image: "default-route-openshift-image-registry.apps.sandbox.cfa.devcloud.intel.com/devcloud-ri/grafana:mcss"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: grafana-mcss
                key: admin-username
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: grafana-mcss
                key: admin-password
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
        readinessProbe:
          httpGet:
            path: /login
            port: 3000
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          name: grafana-config
          readOnly: true
          subPath: datasources.yaml
        - mountPath: /etc/grafana/provisioning/dashboards/grafana-dashboard-provider.yaml
          name: grafana-config
          readOnly: true
          subPath: grafana-dashboard-provider.yaml
        - mountPath: /var/lib/grafana/dashboards/grafana_dashboard.json
          name: grafana-config
          readOnly: true
          subPath: grafana_dashboard.json
      serviceAccountName: 
      serviceAccount: 
      securityContext: {}
      volumes:
      - configMap:
          name: grafana-config
        name: grafana-config
