---
# Source: social-distancing-retail/charts/grafana-mcss/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-mcss
  namespace: devcloudexample
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/metrics'
      prometheus.io/port: '3000'
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-abcxzy
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/managed-by: helm
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana-abcxzy
