---
# Source: social-distancing-retail/charts/mc-ssr/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-mc-ssr
  namespace: devcloudexample
  labels:
    helm.sh/chart: mc-ssr-0.1.0
    app.kubernetes.io/name: mc-ssr
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 8000
  selector:
    app.kubernetes.io/name: mc-ssr
    app.kubernetes.io/instance: release-name
