---
# Source: social-distancing-retail/charts/influxdb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: devcloudexample
  labels:
    app.kubernetes.io/name: influxdb
    app.kubernetes.io/instance: influxdb-abcxzy
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: influxdb
      app.kubernetes.io/instance: influxdb-abcxzy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: influxdb
        app.kubernetes.io/instance: influxdb-abcxzy
    spec:
      serviceAccountName: 
      serviceAccount: 
      containers:
        - name: influxdb
          image: influxdb:1.8
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: persistent
              mountPath: /var/lib/influxdb
      volumes:
        - name: persistent
          persistentVolumeClaim:
            claimName: influxdb
