---
# Source: social-distancing-retail/charts/influxdb/templates/PersistentVolumeClaim.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb
  labels:
    app: release-name-influxdb
    chart: "influxdb-0.1.0"
    release: "release-name"
    heritage: "Helm"
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
